# Generated by Django 5.0.6 on 2024-05-08 20:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('P', 'P'), ('XG', 'XG'), ('M', 'M'), ('P', 'PP'), ('GG', 'GG'), ('G', 'G')], default='', max_length=2)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Quantidade em estoque não pode ser inferior ou igual a zero')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
            ],
        ),
    ]
