# Generated by Django 5.0.6 on 2024-05-08 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Quantidade em estoque não pode ser inferior ou igual a zero.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('P', 'PP'), ('P', 'P'), ('M', 'M'), ('XG', 'XG'), ('G', 'G'), ('GG', 'GG')], default='', max_length=2),
        ),
    ]
