# Generated by Django 5.0.6 on 2024-05-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('GG', 'GG'), ('P', 'PP'), ('XG', 'XG'), ('P', 'P'), ('G', 'G'), ('M', 'M')], default='', max_length=2),
        ),
    ]
