# Generated by Django 5.0.6 on 2024-05-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('P', 'PP'), ('G', 'G'), ('P', 'P'), ('M', 'M'), ('GG', 'GG'), ('XG', 'XG')], default='', max_length=2),
        ),
    ]
