# Generated by Django 5.0.6 on 2024-05-09 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 'Preço do produto não pode ser inferior ou igual a zero.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XG', 'XG'), ('G', 'G'), ('P', 'PP'), ('P', 'P'), ('GG', 'GG'), ('M', 'M')], default='', max_length=2),
        ),
    ]
