# Generated by Django 5.0.6 on 2024-05-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('G', 'G'), ('P', 'P'), ('GG', 'GG'), ('P', 'PP'), ('M', 'M'), ('XG', 'XG')], default='', max_length=2),
        ),
    ]
