# Generated by Django 5.0.6 on 2024-05-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_quantity_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('GG', 'GG'), ('G', 'G'), ('P', 'P'), ('XG', 'XG'), ('P', 'PP')], default='', max_length=2),
        ),
    ]
