# Generated by Django 5.0.6 on 2024-05-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('GG', 'GG'), ('XG', 'XG'), ('G', 'G'), ('P', 'PP'), ('P', 'P'), ('M', 'M')], default='', max_length=2),
        ),
    ]
