# Generated by Django 5.0.6 on 2024-05-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('G', 'G'), ('M', 'M'), ('P', 'PP'), ('P', 'P'), ('GG', 'GG'), ('XG', 'XG')], default='', max_length=2),
        ),
    ]
