# Generated by Django 5.0.6 on 2024-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('P', 'PP'), ('P', 'P'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], default='', max_length=2),
        ),
    ]
