# Generated by Django 5.0.6 on 2024-05-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('PP', 'PP'), ('XG', 'XG'), ('G', 'G'), ('GG', 'GG'), ('P', 'P')], default='', max_length=2),
        ),
    ]
