# Generated by Django 5.0.6 on 2024-05-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kart', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kart',
            name='product',
            field=models.ManyToManyField(related_name='kart', to='product.product'),
        ),
    ]
