# Generated by Django 5.0.6 on 2024-05-09 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kart',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Quantidade no carrinho não pode ser inferior ou igual a zero.')]),
        ),
    ]
