# Generated by Django 5.0.6 on 2024-05-15 18:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0003_kart_quantity'),
        ('product', '0020_alter_product_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kart',
            name='status',
            field=models.IntegerField(choices=[(1, 'No carrinho'), (2, 'Compra encomendada'), (3, 'Esperando pagamento'), (4, 'Na transportadora')], default=1),
        ),
        migrations.AddField(
            model_name='kart',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userKart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kart',
            name='product',
            field=models.ManyToManyField(related_name='productKart', to='product.product'),
        ),
        migrations.AlterField(
            model_name='kart',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Quantidade no carrinho não pode ser inferior ou igual a zero.')]),
        ),
    ]
